### ISSUE TITLE
status shortcodes are hard-coded

### ISSUE THREAD

**Issue by danmarsden** [inspedralbes/moodle-report_attendancetable#3]
Not an easy thing to fix, but it looks like your reports assume that the status codes P, A, L, E are in use - those are the default codes you get on a fresh install of attendance, but many sites customise that list and use other values.
You might want to just drop something into your readme to state that sites must be using the default set of status codes for your report to work as expected.

**Comment by a22ale** [comment]
Thanks, we have added the option of using different acronyms but ended up having to add an explanation on README because adding the option of having other statuses has been proven difficult so far.
